---
title: Severe weather events on population health and economics.
author: "Bjorgvin Reynisson"
output: html_document
---

## Synopsis

## Data Processing

The data is read and we use the str() to take a peek at the data:

```{r, cache=TRUE}
data<-read.csv("repdata-data-StormData.csv.bz2")
str(data)
```

## Analysis

### The analysis of Fatalities and Injuries. Summary statistics for the United States.
We order the dataset based on the fatalities and injuries.

```{r}
ordered_by_fatalities<-data[order(-data$FATALITIES),]
ordered_by_injuries<-data[order(-data$INJURIES),]
```

We will select the top-20 event-types from each dataset and look at those in more detail.

```{r}
top_fatalities<-ordered_by_fatalities[1:20,]
tf<-top_fatalities[,c("EVTYPE", "FATALITIES")]
tf
top_injuries<-ordered_by_injuries[1:20,]
ti<-top_injuries[,c("EVTYPE", "INJURIES")]
ti
```

```{r}
library(plyr)
c_tf<-count(tf, vars = "EVTYPE", wt_var = "FATALITIES")
c_ti<-count(ti, vars = "EVTYPE", wt_var = "INJURIES")
c_tf[order(-c_tf$freq),]
c_ti[order(-c_ti$freq),]
```


## Results
